### ISSUE TITLE
Setup: VM requests

### ISSUE THREAD

**Issue by LIN810116** [ABI-CTT-Group/digital-twin-platform#17]
Request 3 eResearch VM

**Comment by PrasadBabarendaGamage** [comment]
@LIN810116 VM Request 1 submitted for EP1 (https://docs.google.com/document/d/1GGTt92l9ulNdsVYqCy5Ju5yzhgPRn6gIH4XaYM8COHE/edit). We'll wait for a consultation and then submit the requests for the other VMs. I mentioned that we are planning a workshop on 11th Sept.

**Comment by PrasadBabarendaGamage** [comment]
All completed
